Server {
  org.apache.zookeeper.server.auth.DigestLoginModule required
  user_kafka="password";
};

QuorumServer {
  org.apache.zookeeper.server.auth.DigestLoginModule required
  user_kafka="password";
};

QuorumLearner {
  org.apache.zookeeper.server.auth.DigestLoginModule required
  username="kafka"
  password="password";
};
