security.protocol=SASL_SSL

ssl.truststore.location=/home/pyspark/kafka.truststore.jks
ssl.truststore.password=123456
ssl.truststore.type=JKS

sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
  username="admin" \
  password="admin";

# mTLS のときだけ有効化
# ssl.keystore.location=/path/to/kafka.client.keystore.jks
# ssl.keystore.password=123456
# ssl.key.password=123456
# ssl.keystore.type=JKS

# 証明書の SAN/CN と接続ホスト名がズレるローカル検証だけ
# ssl.endpoint.identification.algorithm=