# access-control.name=ranger
# ranger.service.name=TrinoPolicy
# ranger.hadoop.config.resource=/etc/trino/xmls/ranger-policymgr-ssl.xml,/etc/trino/xmls/ranger-trino-audit.xml,/etc/trino/xmls/ranger-trino-security.xml
# ranger.plugin.config.resource=/etc/trino/xmls/ranger-policymgr-ssl.xml,/etc/trino/xmls/ranger-trino-audit.xml,/etc/trino/xmls/ranger-trino-security.xml

access-control.name=allow-all