coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8080
http-server.https.enabled=false
#discovery-server.enabled=true

# 必須: 環境名
node.environment=production

# 必須: ノードIDとデータディレクトリ( This must be unique for every node in the cluster )
node.id=ffffffff-ffff-ffff-ffff-ffffffffffff
#node.data-dir=/data/trino

# 必須: Discovery URI
discovery.uri=http://localhost:8080

# (Trinoにおいてサーバーを直接SSL化する方法より推奨の方法である、)リバプロでSSLをターミネートする
http-server.process-forwarded=true

# 認証を(Password。今回はLDAPに設定)
## 設定ファイルはpassword-authenticator.properties
## 余談だが、keycloakもあるのでOauth認証への変更も可
http-server.authentication.type=PASSWORD

# セキュア設定 for internal
internal-communication.shared-secret=x2H6d63Ciz9B2nTgsOAcx0Cqf7vvg74IadqUS59saFRRGBjL1M21ZbBrGn4u5PCXKZwAHxwwQGedch97P7bqd3LweoCAdzwekOZGpVGQaX+YUQO4WIu3EFnAM5VLZ4qglOqSuS5kt4MS2uGOXSmG7w5IcFls7Df76RVoKQSGYJD73VD8Tsibh/3usTHS+hY1ATvFJv6jvmGLL33gqg88P+Uu//6dzd5SVF6N6Jreq6CUMKP1rUIALuDv2F6uCqByEZ65JSXpkC3F8rG8gSwRoFguZjgRncv6B/LdcCvPzRRSY7stCv6GF+Al/jkdsa3lOyiU4Jl1ju1VO3VViFR4ATufeRSW1s8HlhrpQupu/73IeHfWmqIhjoBo2AUGz8IqywcdczAiTLgdeo/uV3CHxXElFuRH2ohz7wP8xuLPEIn1Ku0Ks5vR6OscseLh/1Vzv/dwBCKZ4tml8VoFIDiUX/EfHQIFUk/o4GKJ6rAYK9ZxWj9d3RiEyPvtNyufQ7C3VA37AYmxs36XOXr79PV+G7XnufR7rDpQpolHdAv57hmhwN5dsjcssjAKyLd0lrpkv8e5l979B4FpDB2S0/APJoDn3AzBmwUXT37x1jz1Ne/mQLchmyGNtImYMRLENMuABQGGQj3lKJ2uy/Iub6spejnnqDmZaKT+QAaIHQZlwYI=

# 認可(access-control)はaccess-control.propertiesにて設定する