# ファイルで簡易的にやるには以下
# group-provider.name=file
# file.group-file=/etc/trino/groups.txt
# file.refresh-period=10s


# Ldap　Group Proveider jarを設定すると直接Ldapと連携できる
# etc/group-provider.properties
# LDAP Group Provider設定
group-provider.name=ldap

# LDAP接続設定
ldap.url=ldap://ldap.local.data.platform:389
ldap.allow-insecure=true

# LDAP管理者認証
ldap.admin-user=cn=admin,dc=local,dc=data,dc=platform
ldap.admin-password=admin

# ユーザー検索設定
ldap.user-base-dn=ou=people,dc=local,dc=data,dc=platform
ldap.user-search-filter=(uid={0})

# memberOf属性ベースのグループ取得
ldap.user-member-of-attribute=memberOf
ldap.group-name-attribute=cn