

# authentication
## https://trino.io/docs/current/security/ldap.html
password-authenticator.name=ldap
ldap.url=ldap://ldap.local.data.platform:389
## 今回LdapはSSL化していないのでinsecureを許容
ldap.allow-insecure=true
ldap.user-base-dn=ou=people,dc=local,dc=data,dc=platform
ldap.bind-dn=cn=admin,dc=local,dc=data,dc=platform
ldap.bind-password=admin
ldap.group-auth-pattern=(uid=${USER})