connector.name=iceberg
iceberg.catalog.type=hive_metastore
hive.metastore.uri=thrift://metastore-thrift.local.data.platform:9083


iceberg.query-partition-filter-required=true

# https://trino.io/docs/current/object-storage/file-system-s3.html
fs.native-s3.enabled=true
s3.aws-access-key=5nCJP6jHFJd7PDsLlT3a
s3.aws-secret-key=FXn6MFKDbNamyMzxiMBGIpgTDFu2r1IfymESfRJd
s3.endpoint=http://minio.local.data.platform:9000
s3.path-style-access=true
# MINOのデフォルトリージョン
s3.region=us-east-1

# Iceberg のセキュリティ設定
iceberg.security=FILE
# Iceberg-only ACL を使う
security.config-file=etc/catalog/iceberg_slv_rules.json
# ルールファイル
security.refresh-period=5s