connector.name=postgresql
# DataSouce側のPostgresをあえて指定する
connection-url=jdbc:postgresql://host.docker.internal:5435/domain_database
connection-user=domain
connection-password=domain

case-insensitive-name-matching = true