Client {
  org.apache.zookeeper.server.auth.DigestLoginModule required
  username="kafka"
  password="password";
};

KafkaServer {
  org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required
  oauth.valid.issuer.uri="http://keycloak:8080/realms/openldap"
  oauth.jwks.endpoint.uri="http://keycloak:8080/realms/openldap/protocol/openid-connect/certs"
  oauth.token.endpoint.uri="http://keycloak:8080/realms/openldap/protocol/openid-connect/token"
  oauth.client.id="kafka_client"
  client_id="kafka_client"
  clientSecret="QwhIdqfojU2lem1PcADpgpmhR9ch70Sz"
  oauth.username.claim="preferred_username"
  sasl.oauthbearer.jwks.endpoint.url="http://keycloak:8080/realms/openldap/protocol/openid-connect/certs"
  oauth.client.secret="VwlpQXLXpD64TFWKfphDwrG19xkxrEtg";

  org.apache.kafka.common.security.plain.PlainLoginModule required
  username="admin"
  password="admin"
  user_admin="admin"
  user_kafka="password"
  serviceName="kafka";


};


client_oauth_ssl.KafkaServer {
  org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required
  oauth.valid.issuer.uri="http://keycloak:8080/realms/openldap"
  oauth.jwks.endpoint.uri="http://keycloak:8080/realms/openldap/protocol/openid-connect/certs"
  oauth.token.endpoint.uri="http://keycloak:8080/realms/openldap/protocol/openid-connect/token"
  unsecuredLoginStringClaim_sub="admin"
  oauth.client.id="kafka_client"
  client_id="kafka_client"
  clientSecret="QwhIdqfojU2lem1PcADpgpmhR9ch70Sz"
  oauth.username.claim="preferred_username"
  sasl.oauthbearer.jwks.endpoint.url="http://keycloak:8080/realms/openldap/protocol/openid-connect/certs"
  oauth.client.secret="VwlpQXLXpD64TFWKfphDwrG19xkxrEtg";
};

client_oauth_ssl.KafkaServer {
  org.apache.kafka.common.security.plain.PlainLoginModule required
  username="admin"
  password="admin"
  user_admin="admin"
  user_kafka="password"
  serviceName="kafka";
};


client_oauth_ssl.KafkaServer {
  org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required
  client_id="kafka_client"
  clientSecret="QwhIdqfojU2lem1PcADpgpmhR9ch70Sz"
  unsecuredLoginStringClaim_sub="sub";
};