Client {
  org.apache.zookeeper.server.auth.DigestLoginModule required
  username="kafka"
  password="password";
};


client_sasl_ssl.KafkaServer {
  org.apache.kafka.common.security.plain.PlainLoginModule required
  username="admin"
  password="admin"
  user_admin="admin"
  user_kafka="password"
  serviceName="kafka";
};

client_sasl_plaintext.KafkaServer {
  org.apache.kafka.common.security.plain.PlainLoginModule required
  username="admin"
  password="admin"
  user_admin="admin"
  user_kafka="password2"
  serviceName="kafka";
};

client_oauth_ssl.KafkaServer {
  org.apache.kafka.common.security.plain.PlainLoginModule required
  username="admin"
  password="admin"
  user_admin="admin"
  user_kafka="password"
  serviceName="kafka";
};
