FROM eclipse-temurin:17-jdk-jammy

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      openssl \
      bash \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /work