# nginx.conf
# いくつか例としてリバースプロキシ経由で認証とSSL化(の終端処理)を実施する

# upstreamで各種転送先を指定（各upstreamに複数指定することで、冗長化も可能）
resolver 127.0.0.11 valid=10s;   # Docker Compose の組み込み DNS

# ② upstream
upstream trino_stream {
    zone trino_stream 64k;       # ★共有メモリを確保（名前・サイズは任意）
    server trino.local.data.platform:8080 resolve;
    keepalive 32;
}

# upstream airflow_stream {
#    server airflow-webserver.local.data.platform:8094 fail_timeout=3s max_fails=1;
#    #server trino_b:8081 backup;
# }

# upstream spark_history_stream {
#    server spark-history-server:18080 fail_timeout=3s max_fails=1;
#    #server trino_b:8081 backup;
# }

server {
    # Httpの場合はHttpsへリダイレクト
    listen 80;
    server_name reverse-proxy.local.data.platform;

    return 301 https://$host$request_uri;
}

server {

    # SSLでのアクセス
    listen 443 ssl;
    server_name reverse-proxy.local.data.platform;

    # 証明書
    ssl_certificate /etc/nginx/certs/server.crt;
    ssl_certificate_key /etc/nginx/certs/server.key;

    # アクセスログの設定
    access_log  /var/log/nginx/localhost.access.log  main;
    error_log  /var/log/nginx/localhost.error.log;

    # https://airflow.apache.org/docs/apache-airflow/stable/howto/run-behind-proxy.html
    # ; location /airflow/ {
    # ;     proxy_pass http://airflow_stream;
    # ;     proxy_set_header Host $http_host;
    # ;     proxy_redirect off;
    # ;     proxy_http_version 1.1;
    # ;     proxy_set_header Upgrade $http_upgrade;
    # ;     proxy_set_header Connection "upgrade";
    # ;     # 後続にHTTPSであるとして伝える
    # ;     proxy_set_header X-Forwarded-Proto https;
    # ; }

    # Trinoサーバーへの終端
    location / {
        proxy_pass              http://trino_stream/;
        proxy_http_version      1.1;
        proxy_set_header        Connection "";
        proxy_set_header        Host            $host;
        proxy_set_header        X-Real-IP       $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto https;

        # タイムアウトを短めに
        proxy_connect_timeout   3s;
        proxy_read_timeout      30s;
        proxy_send_timeout      30s;

        # エラー時に即座に別接続を試す
        proxy_next_upstream     error timeout invalid_header http_502 http_503 http_504;
    }

    # Spark History ServerへBasic認証を入れつつ終端する例
    # Spark History Serverなど(実質的に)認証が入っておらず剥き出しになっているプロダクトを扱う場合に有効
    # location /spark-history/ {
    #     auth_basic "Restricted Access";
    #     # history history
    #     auth_basic_user_file /etc/nginx/.htpasswd_history;

    #     proxy_pass http://spark_history_stream;

    #     keepalive_timeout 10;

    # }

}
