
CREATE TABLE IF NOT EXISTS local_data_platform.slv_entities.user_orders_wide_weather_enriched (
    `latitude`                       DOUBLE COMMENT '緯度',
    `longitude`                      DOUBLE COMMENT '経度',
    `order_id`                       STRING COMMENT '注文ID',
    `user_id`                        STRING COMMENT 'ユーザーID',
    `product_id`                     STRING COMMENT '商品ID',
    `subtotal_usd`                   NUMERIC(10,2) COMMENT '小計_ドル',
    `tax_usd`                        NUMERIC(10,2) COMMENT '税額_ドル',
    `total_usd`                      NUMERIC(10,2) COMMENT '合計_ドル',
    `quantity`                       INT COMMENT '数量_個',
    `status_flag`                           INT COMMENT 'フラグ',
    `order_created_at`               TIMESTAMP COMMENT '注文_作成日時',
    `parent_id`                      STRING COMMENT '親ID',
    `ean_code`                       STRING COMMENT 'EANコード',
    `product_title`                  STRING COMMENT '商品_タイトル',
    `category`                       STRING COMMENT 'カテゴリ',
    `vendor_name`                    STRING COMMENT 'ベンダー_名称',
    `price_usd`                      NUMERIC(10,2) COMMENT '価格_ドル',
    `rating`                         NUMERIC(10,4) COMMENT '評価_RATING',
    `product_created_at`             TIMESTAMP COMMENT '商品_作成日時',
    `product_updated_at`             TIMESTAMP COMMENT '商品_更新日時',
    `product_is_deleted`             BOOLEAN COMMENT '商品_論理削除フラグ',
    `product_deleted_at`             TIMESTAMP COMMENT '商品_論理削除日時',
    `address`                        STRING COMMENT '住所',
    `email`                          STRING COMMENT 'メールアドレス',
    `password`                       STRING COMMENT 'パスワード',
    `user_name`                      STRING COMMENT 'ユーザー名',
    `acquisition_channel`            STRING COMMENT 'チャネル_取得元',
    `birth_date`                     DATE COMMENT '生年月日',
    `zip_code`                       STRING COMMENT '郵便番号',
    `user_created_at`                TIMESTAMP COMMENT 'ユーザー_作成日時',
    `user_updated_at`                TIMESTAMP COMMENT 'ユーザー_更新日時',
    `user_is_deleted`                BOOLEAN COMMENT 'ユーザー_論理削除フラグ',
    `user_deleted_at`                TIMESTAMP COMMENT 'ユーザー_論理削除日時',
    `geo_address`                     STRING COMMENT '都道府県名市区町村＋丁目まで',
    `ingest_date`                    DATE COMMENT 'パーティションキー',
    `_dlq`                         BOOLEAN COMMENT 'DLQフラグ',
    `weather`                        STRING COMMENT '天気',
    `weather_fetched_at`             TIMESTAMP COMMENT '取得日時_天気',
    `temperature_celsius`            DOUBLE COMMENT '気温_摂氏',
    `weather_datetime`               TIMESTAMP COMMENT '論理天気日時(指定時間)'
)
USING iceberg
PARTITIONED BY (`ingest_date`)
TBLPROPERTIES (
    'openlineage.dataset.namespace' = 'local_data_platform.slv_entities',
    'openlineage.dataset.name' = 'user_orders_wide_weather_enriched',
    'write.format.default'            = 'parquet',
    'format-version'                  = '2',
    'write.distribution-mode'         = 'hash',
    'write.target-file-size-bytes'    = '268435456',
    'history.expire.max-snapshot-age-ms'   = '2592000000',
    'history.expire.min-snapshots-to-keep' = '20'
);